# 可以尝试集成config-server来进行配置

server:
  port: 20004

spring:
  application:
    name: platform-gateway
  redis:
    host: 120.27.203.113
    port: 6379
    database: 10
    password: yuanban_redis
  main:
    allow-bean-definition-overriding: true


  cloud:
    gateway:
      # 全局跨域配置
      globalcors:
        cors-configurations:
          '[/**]':
            # 返回的资源共享给请求来源
            allowed-origins:
            - "http://localhost:8080"
            - "http://shop.z.mukewang.com:8080"
            - "http://center.z.mukewang.com"
            - "*"
            # 允许携带cookie、authorization之类的认证信息（暴露给前端的页面）
            allow-credentials: true
            allow-headers: "*"
            allow-methods: "*"
            expose-headers: "*"
            # 标识Options请求可以在浏览器缓存多长时间
            max-age: 600
      discovery:
        locator:
          # gateway去配置中心拉取所有已经注册的服务，并且为它创建默认的路由规则
          # 生产环境一般不会为服务创建默认的路由规则(建议在代码中配置，更直观)
          enabled: false
          # 控制大小写
          lower-case-service-id: true


###########################
#####eureka注册中心配置
###########################
eureka:
  client:
    service-url:
      defaultZone: http://peer1.com:20000/eureka/

#######################################
####开启所有actuator-endpoint
#######################################
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always