server:
  port: 65000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      # 断言配置
      routes:
      - id: yml_path_route
        uri: lb://CLOUD-ITEM-SERVICE
        predicates:
        - Path=/yml/**
        filters:
        - StripPrefix=1

###########################
#####eureka注册中心配置
###########################
eureka:
  client:
    service-url:
      defaultZone: http://peer1.com:20000/eureka/

#######################################
####开启所有actuator-endpoint
#######################################
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always